In [3]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import Sequential

Testing a linear activation function:

In [69]:
linear_layer = tf.keras.layers.Dense(units=1, activation='linear', )

X_train = np.array([[1,2]]).T
Y_train = np.array([[100,200]]).T

print('X_train=\n', X_train, '\nY_train=\n', Y_train)

a1 = linear_layer(X_train)
print('\na1=',a1)

print('\nY_train[0,0]/Y_train[1,0]:',Y_train[0,0]/Y_train[1,0])
print('The ratio of predictions:', a1[0,0]/a1[1,0])

w,b = linear_layer.get_weights()
print('\nw = {}'.format(w))
print('b = {}'.format(b))

X_train=
 [[1]
 [2]] 
Y_train=
 [[100]
 [200]]

a1= tf.Tensor(
[[-0.6496012]
 [-1.2992024]], shape=(2, 1), dtype=float32)

Y_train[0,0]/Y_train[1,0]: 0.5
The ratio of predictions: tf.Tensor(0.5, shape=(), dtype=float32)

w = [[-0.6496012]]
b = [0.]


Testing a logistic activation function:

In [2]:
X_train = np.array([[1,2,3,4,5,6]]).T
Y_train = np.array([[0,0,0,1,1,1]]).reshape(-1,1)

pos = Y_train == 1
neg = Y_train == 0

print(X_train[pos])
print(X_train[neg])

[4 5 6]
[1 2 3]


In [6]:
model = Sequential([tf.keras.layers.Dense(1, input_dim=1, activation='sigmoid', name='L1')])

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


With guess of parameters:

In [24]:
set_w = np.array([[0.6]])
set_b = np.array([0])

logistic_layer = model.get_layer('L1')
logistic_layer.set_weights([set_w, set_b])
w,b = logistic_layer.get_weights()
print('\nw = {}'.format(w))
print('b = {}'.format(b))


w = [[0.6]]
b = [0.]


In [25]:
a1 = model.predict(X_train)
print(a1)

1/1 [==============================] - 0s 60ms/step
[[0.64565635]
 [0.76852477]
 [0.85814893]
 [0.9168273 ]
 [0.95257413]
 [0.97340304]]
