In [1]:
import numpy as np
import tensorflow as tf

The following code represents a neural network with 3 layers with 3, 2 and 1 neurons respectively:

The general layer vector can be written as:

$$\vec{a}^{[j]} = g(\vec{a}^{[j-1]} . \vec{w}_i^{[j]} + b_i^{[j]})$$
for example for $=2$ and $j=1$:

$$\vec{a}^{[1]} = g(\vec{a}^{[0]} . \vec{w}_2^{[1]} + b_2^{[1]})$$

The $W^{[j]}$ matrix has the dimension $(n_{u_{in}} \times n_{u_{out}})$:

- $W^{[1]}$: ($2 \times 3$)
- $W^{[2]}$: ($3 \times 2$)
- $W^{[3]}$: ($2 \times 1$)

$b$ has dimension $(n_{u_{out}}, )$, or

- $b^{[1]}$: ($3,$)
- $b^{[2]}$: ($2,$)
- $b^{[3]}$: ($1,$)


In [13]:
x = np.array([1,2])

W1 = np.array([[1,-3,5],
              [2,4,-6]])
b1 = np.array([-1,1,2])
mw1,nw1 = W1.shape
print(f'The number of features is {mw1} and the number of units/neurons is {nw1} for the first layer.')

W2 = np.array([[1,-3],
              [2,4],
              [5,1]])
b2 = np.array([-1,1])
mw2,nw2 = W2.shape
print(f'The number of features is {mw2} and the number of units/neurons is {nw2} for the second layer.')

W3 = np.array([[1],
              [2]])
b3 = np.array([-1])
mw3,nw3 = W3.shape
print(f'The number of features is {mw3} and the number of units/neurons is {nw3} for the third layer.')


def sigmoid(z):
    return 1/(1+np.exp(-z))

def dense(a_in, W, b):
    """
    a_in: activation vector with shape (n, ), where n is the number of features
    W: weights matrix with shape (n, u), where n is the number of features and u the number of units
    b: bias with shape (u, )

    Returns: a_out (u, )
    """
    m,units = W.shape
    a_out = np.zeros(units)
    for i in range(units):
        w = W[:,i]
        z = np.dot(a_in, w) + b[i]
        a_out[i] = sigmoid(z)
    # print(a_out.shape)
    return a_out

def sequential(x,W1,b1,W2,b2,W3,b3):
    a1 = dense(x, W1, b1)
    a2 = dense(a1, W2, b2)
    a3 = dense(a2, W3, b3)
    return a3

sequential(x,W1,b1,W2,b2,W3,b3)

The number of features is 2 and the number of units/neurons is 3 for the first layer.
The number of features is 3 and the number of units/neurons is 2 for the second layer.
The number of features is 2 and the number of units/neurons is 1 for the third layer.


array([0.83942385])

In [14]:
def prediction(x,W1,b1,W2,b2,W3,b3):
    m,n = x.shape
    probability = np.zeros((m,1))
    for i in range(m):
        s = sequential(x[i],W1,b1,W2,b2,W3,b3)
        probability[i] = float(s)
    return probability

In [15]:
normal = tf.keras.layers.Normalization(axis=-1)

In [19]:
x_test = np.array([[0,0.1],
                   [100.5,2],
                   [-10,-1]])
print(x_test.shape)
xn_test = normal(x_test)

predic = prediction(xn_test,W1,b1,W2,b2,W3,b3)
print(predic)

(3, 2)
[[0.87648605]
 [0.62976062]
 [0.84782889]]


In [20]:
y = np.zeros(len(xn_test))

for i in range(len(y)):
    if predic[i] > 0.5:
        y[i] = 1
    else:
        y[i] = 0

print(y)

[1. 1. 1.]


Now, using a vectorized way, with matrices: $\textbf{A}$, $\textbf{W}$, $\textbf{b}$

In [31]:
X = np.array([[1,2],
              [4,5],
              [10,11]])

def sigmoid(z):
    return 1/(1+np.exp(-z))

def dense(A_in, n_out):
    """
    A_in (ndarray (n, )): activation/data that goes in this layer
    n_out (int):          number of neurons/units of next layer
    A_out
    """
    m,units = A_in.shape
    W = np.random.random((units,n_out))
    b = np.random.random((1,n_out))
    Z = np.dot(A_in, W) + b
    A_out = sigmoid(Z)
    return A_out

def sequential(X):
    a1 = dense(X,3)
    a2 = dense(a1,2)
    a3 = dense(a2,1)
    return a3

def prediction(X_test):
    m,n = X_test.shape
    probability = np.zeros((m,1))
    for i in range(m):
        s = sequential(X_test)[i]
        probability[i] = float(s)
    return probability

x_test = np.array([[0,0.1],
                   [100.5,2],
                   [-10,-1]])
                   
normal = tf.keras.layers.Normalization(axis=-1)
xn_test = normal(x_test)

In [32]:
predic = prediction(xn_test)

y = np.zeros(len(xn_test))

for i in range(len(y)):
    if predic[i] > 0.5:
        y[i] = 1
    else:
        y[i] = 0

print(y)

[1. 1. 1.]
